version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/apps
volumes:
  basic-data:
