version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:latest
    volumes:
      - ./tmp/redis:/data
  app:
    build: .
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/basicapp
    environment:
      REDIS_URL: "redis://redis:6379/"
    depends_on:
      - db
      - redis
