version: "3"
services:
  db:
    image: postgres:13.3
    volumes:
      - basic-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s -b 0.0.0.0
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/apps
volumes:
  basic-data:
