default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: basicapp_development

test:
  <<: *default
  database: basicapp_test

production:
  <<: *default
  database: basicapp_production
  username: basicapp
  password: <%= ENV["BASICAPP_DATABASE_PASSWORD"] %>
